# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_humi',
            fields=[
                ('temp_humi_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.IntegerField(default=0)),
                ('humi', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(verbose_name='date and time')),
            ],
        ),
    ]
